apiVersion: v1
kind: Secret
metadata:
    name: gluetun-secret
    namespace: default
type: Opaque
stringData:
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:RIcqHej+Dw==,iv:fvVhMX0a/P6AMfVlW7BbTsbW/xsv92TaWEZb1Gi1AiE=,tag:HbjYi3nP7BFRfXkTZlPlIA==,type:str]
    VPN_TYPE: ENC[AES256_GCM,data:mctZGEbAPw==,iv:Z9VEatlrWOpvVXfjChHRyL2wfIFco09lEjfCqYJ6HT4=,tag:9cb6iLaJn5IdYG9gBlxx/w==,type:str]
    OPENVPN_USER: ENC[AES256_GCM,data:kxrfQlaSQJnqY1WI0JHeFX1p24vkBrnx,iv:aZFF8hMW+103CnN/tFbExVVo4bNPVuxLyU8KXqpKDWk=,tag:JWCmfdokTYhV9dnSE6+HNg==,type:str]
    OPENVPN_PASSWORD: ENC[AES256_GCM,data:1PgSYNifE041CeuFOWRVM1tsGGVabCms,iv:KprvrtoGOQgXLVBNSutJKFGuxBkuXYfKNPlTxdqpMeE=,tag:AId9T0FRQRw3wHxgx+HNKg==,type:str]
    FIREWALL_VPN_INPUT_PORTS: ENC[AES256_GCM,data:14PjGTg=,iv:ntE8LodN0DXX4HRzcjHcnBbIFn5r+Ayl72EbOV98ra0=,tag:jpucBx1Nfshy0ubV/0/Q6g==,type:str]
sops:
    age:
        - recipient: age1gekuxnpd95l5j8gsvmpsn2mewnevd0c5y5v66p4trzcqhmpn0svqkmnyy7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYWhDK3Q3bzM0SENHaEV2
            RTIxZkpjbzJNbWN3eDkvMzNRc250S3dGOVU4Cm5NM0JYWFlJRVZ1cW94RCthYktT
            V0RRTlhCZitLTWNubVlGaFBqL21icEUKLS0tIERTM1ltc0oxSTNkUUZUSkk0ZlJN
            cStiUHd1eUROQk4reTZ3dkdUcnhzNGMK5s0/IjXUJOWMcpVGvNvrF1SjoqtqzUbR
            bFOK2mqAA2AeLZB1gY/TIRNmAYZU55KJj665LtaQuX1T3XJi+5qFAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T00:27:27Z"
    mac: ENC[AES256_GCM,data:1KJcZbG0mWw2IViOtp77b0zMcc7NiZV2xV1bw4+PFCa9kKcemD5lis0/YZBHzpWG0+bsUCnTbu18o84x9+qaYPZhlWVPPeelzWdzHxOne19k0K+JLOIpQAAv+LbqBoNAtDaUEf6a2oWhOV+my2ak4JcCmgDC+9Eb33gjKTUpX2Q=,iv:6bCorcuoKLrLaUvQzVMrErMDROnSKpaS0Qg7XYsiJIc=,tag:pWgkBc1oSV3KsJ0zadYd+A==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
