apiVersion: v1
kind: Secret
metadata:
    name: n8n-smtp-secret
    namespace: default
type: Opaque
stringData:
    N8N_EMAIL_MODE: ENC[AES256_GCM,data:Cs/P2A==,iv:JJiav1HB+xGI5bIy+OMKgo4jOLhOu+wbSp4uciT5tqg=,tag:Dt7XbMd1yXBkHkwuodoWug==,type:str]
    N8N_SMTP_HOST: ENC[AES256_GCM,data:kzKselsqudiuFf5rOtk=,iv:LDSSD4FtOm9lOOI1t0ozSJvN/FoPjh36emuHPbcIWqI=,tag:7XQM5T3ppWD0nNN4pKc5fA==,type:str]
    #ENC[AES256_GCM,data:Prjjn+2xGSwfe6+YFYo+,iv:CcatryAJHn22pFFWYDZ9jn1tNJMY0y9LgMMtVxX66YE=,tag:YiPmWj3vyWvjokn0k1Twrg==,type:comment]
    N8N_SMTP_PORT: ENC[AES256_GCM,data:KtwD,iv:WSi9Vj1ltM94/T3M0vU7D//JnpEW4He8lhkltBlNAsw=,tag:YRwKDyhedFEysMRQjda5Ig==,type:str]
    #ENC[AES256_GCM,data:f1I4iZ0bZbBk1OnsoRgSswa/Boh6ZpxM,iv:VKR6Nh2tpbQee7IqSMDJl0xA+IRzGalz8Tz679MjfbM=,tag:SjZ908v7mdDmWRiZUn+jYw==,type:comment]
    N8N_SMTP_USER: ENC[AES256_GCM,data:9nONVWFFIqEky4TXN58qxovEXFNfg1RY,iv:n64qfCG8Vgrekm2fCs5RjDW8Mu8UeA1DF2CI7CaEWVo=,tag:xRyaQegQ2iT3odfUhg/FBg==,type:str]
    N8N_SMTP_PASS: ENC[AES256_GCM,data:iYn45KG/QH1dE/ezeONGWTeaLA==,iv:qwgafGkmSi3+yCU6nxyel5h3CflRXHzU3m8oYUNn+Zc=,tag:u72KL+dqNygk2/QGKdL/3A==,type:str]
    N8N_SMTP_SSL: ENC[AES256_GCM,data:NX6jXg==,iv:rnC57RGmEz5temCehBssXEPNft1N6CWLn2z2hMWkbac=,tag:LwK5I6jJv1UhvDRpR9jRLg==,type:str]
sops:
    age:
        - recipient: age1gekuxnpd95l5j8gsvmpsn2mewnevd0c5y5v66p4trzcqhmpn0svqkmnyy7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYWhDK3Q3bzM0SENHaEV2
            RTIxZkpjbzJNbWN3eDkvMzNRc250S3dGOVU4Cm5NM0JYWFlJRVZ1cW94RCthYktT
            V0RRTlhCZitLTWNubVlGaFBqL21icEUKLS0tIERTM1ltc0oxSTNkUUZUSkk0ZlJN
            cStiUHd1eUROQk4reTZ3dkdUcnhzNGMK5s0/IjXUJOWMcpVGvNvrF1SjoqtqzUbR
            bFOK2mqAA2AeLZB1gY/TIRNmAYZU55KJj665LtaQuX1T3XJi+5qFAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-02T19:13:52Z"
    mac: ENC[AES256_GCM,data:VT5PqJP5giiZhAg7uWcsHv8kCt48jb+Fqs4Vvzoxylu1aY6+iAkMhmkFzf5eHm8oVNTFYh8VEtjYOCANQCVfA7qgeALA2l9Hrc+/Gx4aZIyLUdUFMk3LoApu2grXPuC/pVqRRmMOI1jxAuxbWK0fHHeCzKfxD9FfkZRwrmh+iQ8=,iv:X84SxlaOL9TH2aThQx1F+Mt+9u/+psIKcXd0WZH+PU0=,tag:S67WVEQF+r1znFQoNqPzdQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
