apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-default-resource
  namespace: storage
data:
  default-resource.yaml: |
    "backup-target": "s3://hiro-longhorn-backups@us-east-1/"
    "backup-target-credential-secret": "longhorn-s3-backup-secret"
    "backupstore-poll-interval": "180"