apiVersion: v1
kind: Secret
metadata:
  name: longhorn-s3-backup-secret"
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:mIeTel/apnGutiZeFwQERwlL0LU=,iv:6l28alyDu3mQtcVObW7FRJ12zGBdo/MQDxBc8KQioTY=,tag:Wiee3S58ipxx5oLioh4rzQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:WKJpmiodKzOTf7CH2yco2mzHBfaaOOjkd2He2FOTpql6Dk1Ef6F2/Q==,iv:BKKHQA9GRCAp2a8grOJS3UhcOM4P9mWV6kk7kWQKfJk=,tag:weapaN2PNApuT1sFXnP3qg==,type:str]
sops:
  age:
    - recipient: age1gekuxnpd95l5j8gsvmpsn2mewnevd0c5y5v66p4trzcqhmpn0svqkmnyy7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQVk3VlJLc3V4LzVZTEVL
        OXoraWw3OXhiaFhtOWR0cGNmTDk5bEdHTVVRCjVmSlhHVVlQQ3BUdm92SGoxcFhG
        THFLSGQ4dmRjbXZuWDE4QlNWTDVCWHMKLS0tIGRmMkxTZnNlS0pBb3hEYi83QlR4
        SjUzUDdPVUU3V3p3TEdMbXcyOGxOTEkKFuKRsYD3vV1SCTUxQxKoGXwWs5VxLY8G
        toWgXBB4QFMfRNnTUVkOVqxF91dxlNwkdxitXc72WC5BTT0b3l4GeA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T19:47:47Z"
  mac: ENC[AES256_GCM,data:gm9MmSeFbQhGuDtpU6R8RtVpJXkwbAuLsAQ8rYBONJz9L3n54Q8lL5SJfbYO9IQuHkCr7brO/At7lYLUbcuBFuTwX05zVKn31CPsZ34usZxiAVNz0cfahvtmiGy14GnHTQmqRy2tLf2aAyK/A6MoyQbU3Zk5DzZGdE0fiiWm65g=,iv:G5CBfHguQeaMZoNZGelqq52Zwtggt1I3b7hIKf3yBF0=,tag:2qkVqlgrDa8dqMc7V8SsWg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
