apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:0LLAlNB9fzW4CwuPtO/7DRQfx9bcz6RmzkFI+p/etoTlIFGi45iusA==,iv:RNVUTEN8w/4p1Jd9SQ6uOtsMwKr5cfVSpgzOS+xPJ9Y=,tag:DvEeLm1d/ietuGCNYcVZ5g==,type:str]
sops:
  age:
    - recipient: age1gekuxnpd95l5j8gsvmpsn2mewnevd0c5y5v66p4trzcqhmpn0svqkmnyy7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZb0pSOC9ObTBaN3hianM1
        YnJpWFJDd0kzVGNaTm5xMWFyeCtURWxsY2hRCnptV0M3KzJkcFJSQldZN1hVVGQ1
        Z0ZKbitGbGRJZ3JSZlo1TGZkdUxKQUUKLS0tIER0STduVGt2Qk0ycVhZUHFGbEFO
        VFJwM0ZkTmJ1Mm15N0toMDVvSW9pVDAKquQv5frNqmDgADUhSgfcSWmn3ZuJQVO/
        cl00NfRU8JhCWFqjIESozgjxgVN4jlSvB7TLZKSeWUtXZE1JmW3izQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T19:55:33Z"
  mac: ENC[AES256_GCM,data:ZkJNwl2mulLvCxcdrA6gC6EX3swmCwcwN4a6YisarJYXNIGSbDLpauqSpQSAlAl1eD93/5ALnbZNC0TrgVNtXrqNVmOKZRDzwqS8F3zpJ45F+6nxBck4vmAOnAFSIJ9FTQzDXZ/Vozv/YvSRHQwkKBLapu/X/1e+LQ1UUK5R/0k=,iv:aF7qOtdmMMi6l6iPaaB7VG3KDpwjZ8DB7UNSGWbiX3M=,tag:lGbPcvE69ttACaxlgjpOCg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
