apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:518p69AlEcg42n0=,iv:1vG65lNqIIX6jY88eF63+BhIRX6JJ1O/XDhbb2J6rnE=,tag:BpKRQIKyp29Uk4YOieEMaw==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:uzkf7cTXktiQxhvZBTAY,iv:ZVlTZKK95L3/sO4rPXwLPboa/GGTwRIEVPSUvTq6aqA=,tag:IM8XKuSzRu9V5rrI1SHEQQ==,type:str]
sops:
    age:
        - recipient: age1gekuxnpd95l5j8gsvmpsn2mewnevd0c5y5v66p4trzcqhmpn0svqkmnyy7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWlVzeTNBUXAvMGdaRXU3
            dHQvWmphSFhKbHJuckdLS3Zia29WZUY2emxjCmpjQkhWY1JITHhhdDltcUwyWFhu
            d1RqVEVUSHh0YXJhRlladTkyUW5HY0UKLS0tIG15Yk51TEVtYi9BUk84M2JnM1Vw
            K0R0RVdZamc3Si85Q3ZQdVlGVVowSDgKvZooSwZAo2q9tRGF8HriMxZfedCr7AMX
            /s5c3cy7+rnV5CdkW635crxhl3tRy4ZTjI6uSfOnqx+oz9TlAiMLzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-28T16:25:58Z"
    mac: ENC[AES256_GCM,data:t0JL2dmpX9rFbVchjgxnBejCXvrBn5GoJm1qeR3JzSdMMYtra5QHAcWeSFwLqOZITWOSrr3EJTmmID9WPtGx313l/AdhLQAIB8OJKL/bsiWrhj4JfSBY9XxZm0B4mOIrZPIqFtoNz7ECNO+SmlLEF9XKHRZWz7K/IhnD2vrenjA=,iv:SHKnmLCL5cP6dtlnhJ7QhmkyjnMN/VJozTYSjZZsElw=,tag:gr5X7Xj6lMWcxGaXriFoGA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
