apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:RlfsV+6MC71M3qI=,iv:QgywaW84n8VYVEdtpQl+rYGhvwR2rhRRoI7IN4nfOHI=,tag:ZoE2vCPzEKlSc+j5OCeYYA==,type:str]
sops:
  age:
    - recipient: age1gekuxnpd95l5j8gsvmpsn2mewnevd0c5y5v66p4trzcqhmpn0svqkmnyy7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBd3lrL0xRdGZPSTl4Z2tR
        ZmVCU3c4ZXNvYldLNU5UNmlhK2dIMmZIbFFRCm9jQnNPVTdOdlJuR3V0M3djVjBj
        K29meU1nZG1Id3FxV2FIWS9NTUIwbXcKLS0tIDgwQ0Jmd25tNXRCbVJhWXZGOXJu
        OUNadTViaThMVU83ekd5a1FqcEE3emsKDYhAz/XVpDLCnQ/h8P9SOD9MsAeqUnpR
        XKvBW91Nk2ByVT5dJtXkhkrg5VlQ3kGvFXQ9bGuXzD0lUYBoE0VxAQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T19:55:33Z"
  mac: ENC[AES256_GCM,data:HnfAFWo/R4yIKilkM6yUvVFAp38u5DdiwcpT0kS7/9oQqSL9pOeNqjRGP0V8uin2WDt81fCUMx8etSp1yF2Hld9ZZRwXNZdU3JriBAbB3qHFVEH5xYXjPpE3LXvlt14+2ULA+iPot75fPiCOevUdGxsElFgKmaK3pSC6QxwsfiI=,iv:fPJOMn65493DgDWLWQtviNFQ6hcrUyL2cDexgV338Jk=,tag:epc2C1wHeriZGH/jXit/eA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
