apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:CMawPnve4p+/FXg/1TqF7ibOdWDq900MupGCrHbRgQw=,iv:7n3QT8NUaRYzTGOVZWrgckvjB68vi0GCpJDXFC4oouE=,tag:59WyZz22rSQlcnU7Zs9jsQ==,type:str]
sops:
  age:
    - recipient: age1gekuxnpd95l5j8gsvmpsn2mewnevd0c5y5v66p4trzcqhmpn0svqkmnyy7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdXRhZmFyZ2duaCs3dlN3
        QTI4Wng4SjIyRk95cU1XQ1pMb05vMS9OVjI0CmlQYmtpV1NrMm1PSENGWmg4K2RB
        UVFDWWNDbUNyd05CT0tydXBHd2RlTkkKLS0tIGdoQWk3S01PYUVDTTFKMkUxeTE5
        OTVnWmo3SHlWdTdjdjlRdHF0WVRVWU0KbIDi/wp0M0P4W6YWIVlu8upNLPLNP+2X
        +n7vc4UUwv6SsqjPUWSPAQTBkASgbK3OYrD5oG9VvmNzLSQ7YsyIoQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T19:55:33Z"
  mac: ENC[AES256_GCM,data:/kTgYyXq1CUPOuFIokH6uYj+aIo4Y/z/F87LDD+ijmcbRkWt8it0N6f6z1CASmuKwdN+G/ZyK0ryYiwzuUTlH6T55sjJgI4Z1/t+6Bf8MKYoQIhgVEtshC8aXBoyqc/JwB2IHQOzH7JpAaOOT5y8ew5rcvtwkKuxNoHLA2L7ato=,iv:e1TwFBU65nYVWm+Q0YL02cuLEZu/bw9O6lg4rgXLvDs=,tag:zGgpHmY0RvsSb3Htqro4xQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
