---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: scanner-files
spec:
  chartRef:
    kind: OCIRepository
    name: scanner-files
  interval: 1h
  values:
    controllers:
      main:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: docker.io/dperson/samba
              tag: latest
            env:
              TZ: "${TIMEZONE}"
              # PERMISSIONS: true
              SHARE: public;/srv;yes;no;yes;all
              USERID: 0     # This sets the user to root
              GROUPID: 0    # This sets the group to root
              SMB: false   # Disable SMB2, since the HP476 printer seems to support only SMB1.  If unset the minumum is SMB2_10.  When I tested the HP476 with SMB2 enabled on an openmediavault server, it seemed to write work.  This image may set the patch level too high.
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 512Mi
          browser:
            image:
              repository: docker.io/filebrowser/filebrowser
              tag: v2.54.0
            env:
              TZ: "${TIMEZONE}"
              FB_DATABASE: /config/filebrowser.db
              FB_ROOT: /srv
              FB_LOG: stdout
              FB_NOAUTH: true
              FB_PORT: &port 8080
              PUID: 0
              GUID: 0

    service:
      app:
        ports:
          smb1:
            port: 139
            protocol: TCP
          smb2:
            port: 445
            protocol: TCP
      browser:
        ports:
          http:
            port: *port

    route:
      app:
        kind: TCPRoute
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}", "scans.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: smb445
        rules:
          - backendRefs:
              - identifier: app
                port: 139
              - identifier: app
                port: 445
      browser:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: mdi:folder
          gethomepage.dev/title: Scanner Files
          gethomepage.dev/description: "File Scanning and Sharing Platform"
          gethomepage.dev/group: "Home Services"
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}", "scans.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: browser
                port: *port

    persistence:
      srv:
        existingClaim: scanner-files