apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fission
  namespace: default
spec:
  interval: 1h
  chart:
    spec:
      chart: fission-all
      version: 1.21.0
      sourceRef:
        kind: HelmRepository
        name: fission-charts
  values:
  # https://artifacthub.io/packages/helm/fission-charts/fission-all
  # https://github.com/fission/fission/blob/main/charts/fission-all/values.yaml