---
# yaml-language-server: $schema=https://crd.movishell.pl/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: TCPRoute
metadata:
  name: minecraft
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Games
    gethomepage.dev/name: Minecraft
    gethomepage.dev/icon: minecraft.svg
    gethomepage.dev/pod-selector: app.kubernetes.io/name=minecraft
    gethomepage.dev/widget.type: minecraft
    gethomepage.dev/widget.url: udp://minecraft.default:25565
spec:
  hostnames: ["minecraft.${SECRET_DOMAIN}"]
  parentRefs:
    - name: envoy-internal
      namespace: network
      sectionName: minecraft
  rules:
    - backendRefs:
        - name: minecraft
          port: 25565

