apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:HCtozipdk5RyCmf5IEaC1b+5loK0rjVjW0NCCDty12JZYGCdj19pF77q40cf0vGxwrsV7/Ce9KJun2IxwCW/BAJsVo//MV6ghre/fLf21stUrlPkQi6aEGHNjoiffhMafi9RGjbOzYKx30W7leVEThCoV5ZY+FHW3m/yBjx6L9OMYVsePZBS6m94qNTx8crYXmPOtBPqc7yIcdQ9oWhp8ZV2eNI7aGW2aGXdTEUmA5oWIzQJ,iv:7x+NetJ7/aAOkIYOrkIpevNgA8vQLrLzMVrTSigcKEg=,tag:OSyo6QBo8i7FHZFUAO4kew==,type:str]
sops:
  age:
    - recipient: age1gekuxnpd95l5j8gsvmpsn2mewnevd0c5y5v66p4trzcqhmpn0svqkmnyy7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4anoxeGlPQ2VZd0ZLcG5U
        K1VSOFoxM0ttd1pNYlFodVNMa2lGSnJpYlJrCktveENUbWpMV2tZeTJEc0pXRDVB
        WWN4eHdob3FOa2poSEkzSHNBZzlEYkkKLS0tIHZmYnRNVll4QTFuSkxDQlh6Zmdy
        Y24vNUVuUEptNE5ST3I4TlFNSnp0L0kK8P05/0K7qfvWSCdtCkhLlnmEmJdJAIHD
        LqDq2d0f0eX66MMTOfAlaTxWgeiC+V2fEsOWsNO7HzcEQ1BFZzs3zw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T19:55:33Z"
  mac: ENC[AES256_GCM,data:NjtwByBQE1ZBUnsGmIM0qlSYmJB6gR1GNAbCPQw92dQHoZXp15YyO/VmqOwS51qAhfDvIZYhk4p0ARea2ADwV4KGanq2HEfatPTS41TnSx1V1JV61IHHkdSO5KUW2W/n5FLnF/2Xx0MR3AqZXlx+Yof062DbQpYMHC/tHHq56Nw=,iv:MfRm3S9Z3soWueTD5ioHaEDnR3zVmoZkLjLNmupdGm4=,tag:fd9M7hOyFIcu7UB/cjEhpQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
