apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Z6x96WsJVewikP22IzbmDOrBejD7dmTGwNnoKzqAvbMNwcvAv8P0Tg==,iv:WfHlnitmPgww6/bDwrigB6C7jCzYKKWzDjoDWlyy1xk=,tag:GEGxgR7hYmtkQLWzWkpK4A==,type:str]
sops:
  age:
    - recipient: age1gekuxnpd95l5j8gsvmpsn2mewnevd0c5y5v66p4trzcqhmpn0svqkmnyy7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVXNlNUNUTWoyNnhmcFZD
        L1YyOGVTcmN5blIzNUk3NDFjcmpaaDlRU2hVCmxlRm9MeTdnZzd4dW96MTRKVmhs
        aTMveGdESk1qYXEvNnZRNG9pamJUcWMKLS0tIGlJUVgrb2dSa0Y4c201UmVSUjdu
        aWpVdnl2Kzk0cGREenhDT1BVdTJzcFkKNQOsDZZAV2mvKnC+db0OVIAWKEwVkU9i
        8zLC2Ww+6zubsc79dc/mGlsyrkSMH0rF5VcyeQ5VZhy/5uTF/uvgFQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T19:55:33Z"
  mac: ENC[AES256_GCM,data:Up0CgegHAqfEVqtxhp+3opaE7w7CTtnc44OgMKB3RQaUrQy1WZ0NSp6iemlJL52Sbftf/7uAU1D5FfwFOx5wYWas7uKL0B79G8eWztn7hbofrw1jL4msedbr9u++VUSvEqLm1Y2srpOTLKaL79zhugKx325hDL/q6YuHxKY0LHs=,iv:5d1VpJausC/zUspvRXads1XTM0dnYWBF0PmeBTmcSUE=,tag:ArWMKq2l49eVrVmEK/f93Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
