---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.25.20:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.25.20"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "hiro-cmp-01"
    ipAddress: "192.168.25.21"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/613e1592b2da41ae5e265e8789429f22e121aab91cb4deb6bc3c0b6262961245
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:4b:43:c7"
        dhcp: false
        addresses:
          - "192.168.25.21/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.25.1"
        mtu: 1500
        vip:
          ip: "192.168.25.20"
  - hostname: "hiro-cmp-02"
    ipAddress: "192.168.25.22"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/613e1592b2da41ae5e265e8789429f22e121aab91cb4deb6bc3c0b6262961245
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:1d:a0:92"
        dhcp: false
        addresses:
          - "192.168.25.22/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.25.1"
        mtu: 1500
        vip:
          ip: "192.168.25.20"
  - hostname: "hiro-cmp-03"
    ipAddress: "192.168.25.23"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/613e1592b2da41ae5e265e8789429f22e121aab91cb4deb6bc3c0b6262961245
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:39:c5:4c"
        dhcp: false
        addresses:
          - "192.168.25.23/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.25.1"
        mtu: 1500
        vip:
          ip: "192.168.25.20"
  - hostname: "hiro-cmp-04"
    ipAddress: "192.168.25.24"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/613e1592b2da41ae5e265e8789429f22e121aab91cb4deb6bc3c0b6262961245
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:ac:0a:05"
        dhcp: false
        addresses:
          - "192.168.25.24/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.25.1"
        mtu: 1500
        vip:
          ip: "192.168.25.20"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"
  - "@./patches/global/machine-volumes.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"

