apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
  namespace: network
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "eth1",
      "ipam": {
        "type": "static",
        "routes": [
          {
            "dst": "192.168.0.0/16", "gw": "192.168.1.1"
          }
      }
    }'
